spring:
  application:
    name: order-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/userdb
    username: root
    password: root
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always